# Generated by Django 4.1.7 on 2023-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platos',
            options={'verbose_name_plural': 'Platos'},
        ),
        migrations.AddField(
            model_name='platos',
            name='procedencia',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='platos',
            name='nombre',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
